spring:
  profiles:
#    active: dev
    active: test
  mail:
    host: smtp.gmail.com
    port: 587
    username: prokatradom@gmail.com
    password: procatAS2107
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

aws:
  secret-key: BquqVoXGV1U8Ok+wKNIIXxZaofCoOP9krSmFt0Im
  access-key: AKIA4BDR5OXQH2D4ZQCQ
  bucket-name: geo-rent-bucket
  and-point-url: https://georent.ua/
  expires-in: 60000
  file-size-max: 200000

app:
  jwt:
    secretKey: glutton-oversight-rare-shine-unchain-unboxed
    expiresIn: 3600000
---

spring:
  profiles: test

  datasource:
    url: jdbc:h2:mem:georentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: geo
    password: geo

    hikari:
      maximum-pool-size: 10
      connectionTimeout: 3000
      leakDetectionThreshold: 30000
#      minimum-idle: 1
      max-lifetime: 120000
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        show_sql: false
        use_sql_comments: false
        format_sql: true
    show-sql: false

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

logging:
  config: classpath:logback-local.xml
---
spring:
  profiles: dev

  datasource:
#    url: jdbc:mysql://localhost:3306/test
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin

    hikari:
      maximum-pool-size: 10
      connectionTimeout: 3000
      leakDetectionThreshold: 30000
      #      minimum-idle: 1
      max-lifetime: 120000
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        show_sql: false
        use_sql_comments: false
        format_sql: true
    show-sql: false
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.json

logging:
  config: classpath:logback-dev.xml
